target 'sampleapp-ios-swift' do
  platform :ios, '12.4'
  use_frameworks!

  pod 'AppCenter'
  pod 'AppCenter/Push'
  
  target 'sampleapp-ios-swiftUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'VSMobileCenterExtensions'
  end

end
