// This file has been autogenerated from a class added in the UI designer.

using System;
using Acquaint.Util;
using Foundation;
using UIKit;

namespace Acquaint.Native.iOS
{
	public partial class SetupViewController : UIViewController
	{
		UIColor ValidEntryColor;
		readonly UIColor InvalidEntryColor = UIColor.Red;

		public SetupViewController(IntPtr handle) : base(handle) { }

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			ValidEntryColor = DataPartitionPhraseEntry.TextColor;

			DataPartitionPhraseEntry.TouchUpInside += HandleDataPartitionPhraseEntryTouchUpInside;

			ContinueButton.TouchUpInside += HandleContinueButtonTouchUpInside;

			InstructionsLabel.Text =
				"The phrase is a key that will separate your data from everyone else's data. Make it unique." +
				"\n\n" +
				"Enter this same phrase on any device running Acquaint that you'd like to sync data with.";

			NavigationController.ApplyStyle();
		}

		void HandleDataPartitionPhraseEntryTouchUpInside(object sender, EventArgs ea)
		{
			if (!string.IsNullOrWhiteSpace(DataPartitionPhraseEntry.Text))
			{
				DataPartitionPhraseEntry.TextColor = ValidEntryColor;
			}
		}

		void HandleContinueButtonTouchUpInside(object sender, EventArgs ea)
		{
			if (string.IsNullOrWhiteSpace(DataPartitionPhraseEntry.Text))
			{
				DataPartitionPhraseEntry.AttributedPlaceholder = 
					new NSAttributedString(
						DataPartitionPhraseEntry.Placeholder, 
						UIFont.SystemFontOfSize(UIFont.SystemFontSize), 
						InvalidEntryColor);

				DataPartitionPhraseEntry.BecomeFirstResponder();

				return;
			}

			Settings.DataPartitionPhrase = DataPartitionPhraseEntry.Text;

			DismissViewController(true, null);
		}
	}
}
